### ISSUE TITLE
Cannot pull more than 25 results at a time

### ISSUE THREAD

**Issue by bilwaj** [indeedlabs/indeed-python#3]
Setting the 'limit' parameter in the search to more than 25 has no effect on the output. The website shows many more results

**Comment by jboutros** [comment]
This is a part of the design of Indeed's API, the upper bound for returned results from the API is 25.

**Comment by smalik** [comment]
Is there any way to get an exemption from this policy?

**Comment by jboutros** [comment]
I'm not totally sure- you would have to contact Indeed directly about this to inquire about an exemption. This is the contact link from the API site: https://ads.indeed.com/contact_indeed?hl=en&co=US

It says employers on the form, but it should go to the API team as well.
